server:
  port: 8083

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: springvaultbank@gmail.com
    password: evumgdxmoyvlxywz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
  application:
    name: NOTIFICATION-SERVICE
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:9296
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-21987908.okta.com/oauth2/default
      client:
        registration:
          internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oa9kxc13lNeKzRpP5d7
            client-secret: 4ahtxCMwLfhX2tDFJq1hQhmP1PU2pZ_X1jhafOwD
        provider:
          okta:
            issuer-uri: https://dev-21987908.okta.com/oauth2/default

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
