server:
  port: 8083

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: springvaultbank@gmail.com
    password: evumgdxmoyvlxywz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
  application:
    name: NOTIFICATION-SERVICE
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-90530851.okta.com/oauth2/default
      client:
        registration:
          internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oa9rt67l0cQQNQoE5d7
            client-secret: 8FHtFpCFVF7PkgFuWvxRKlyBcf4Lxu0UfIlzBxCo
        provider:
          okta:
            issuer-uri: https://dev-90530851.okta.com/oauth2/default

