server:
  port: 8085

spring:
  application:
    name: NOTIFICATION-SERVICE
  mail:
    host: smtp.gmail.com
    port: 587
    username: springvaultbank@gmail.com
    password: xcgyxcrxhvjrgaed
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cloud:
    config:
      import-check:
        enabled: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}