server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
  cloud:
    discovery:
      enabled: true
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - Authorization
              - Content-Type
            exposedHeaders:
              - Authorization
      routes:
        - id: ACCOUNT-SERVICE
          uri: http://account-service-svc
          predicates:
            - Path=/account/**
        - id: CUSTOMER-SERVICE
          uri: http://customer-service-svc
          predicates:
            - Path=/customer/**
        - id: NOTIFICATION-SERVICE
          uri: http://notification-service-svc
          predicates:
            - Path=/notification/**
        - id: TRANSACTION-SERVICE
          uri: http://transaction-service-svc
          predicates:
            - Path=/transaction/**

okta:
  oauth2:
    issuer: https://dev-90530851.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa9rt67l0cQQNQoE5d7
    client-secret: 8FHtFpCFVF7PkgFuWvxRKlyBcf4Lxu0UfIlzBxCo
    scope: openid, profile, email, offline_access


