apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service-app
spec:
  selector:
    matchLabels:
      app: transaction-service-app
  template:
    metadata:
      labels:
        app: transaction-service-app
    spec:
      containers:
        - name: transaction-service-app
          image: docksterharsha/transactionservice:0.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  key: config_url
                  name: config-cm
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongodb-cm
                  key: hostname

---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service-svc
spec:
  selector:
    app: transaction-service-app
  ports:
    - port: 80
      targetPort: 8082
