apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-app
spec:
  selector:
    matchLabels:
      app: account-service-app
  template:
    metadata:
      labels:
        app: account-service-app
    spec:
      containers:
        - name: account-service-app
          image: docksterharsha/accountservice:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: EUREKA_SERVICE_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: eureka_service_address
                  name: eureka-cm
            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  key: config_url
                  name: config-cm
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-cm
                  key: hostname

---
apiVersion: v1
kind: Service
metadata:
  name: account-service-svc
spec:
  selector:
    app: account-service-app
  ports:
    - port: 80
      targetPort: 8080
