server:
  port: 9296

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    discovery:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/harsha-commit/spring-vault-config   # Git repository URI
          clone-on-start: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}